export { default as Button } from '../GenericComponents/Button/button';
export { default as InputField } from '../GenericComponents/TextField/textField';
export { default as PhoneField } from '../GenericComponents/PhNoField/phNoFiled';
export { default as CheckBox } from "../GenericComponents/CheckBox/checkBox";
export { default as Tag } from "../GenericComponents/Tag/tag";
export { default as Image } from "../GenericComponents/Image/image";
export { default as Navbar } from "../GenericComponents/Navbar/navbar";
export { default as DropDown } from "../GenericComponents/DropDown/dropDown";
export { default as PhaseVideoCard } from "../GenericComponents/PhaseVideoCard/phaseVideoCard";
export { default as SERVICECARD } from "../GenericComponents/ServiceCard/serviceCard";
export { default as FileUploaderArea } from '../GenericComponents/Fileuploader/fileUploaderArea'
export { default as UploaderImg } from '../GenericComponents/UploaderImg/uploaderImg';
export { default as Avatar } from '../GenericComponents/Avatar/avatar';
export { default as Upload } from '../Helpers/upload';
export { default as Stepper } from '../GenericComponents/Stepper/stepper';
export { default as ProjectCard } from '../GenericComponents/ProjectCard/projectCard';
export { default as ServiceCard } from '../GenericComponents/ServiceCard/serviceCard';
export { default as ScrollMenu } from '../GenericComponents/scrollMenu/scrollMenu';
